# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Add title and description

Revision ID: 03595bfbe826
Revises: f7df23ff0c1d
Create Date: 2026-07-08 21:39:21.975842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "03595bfbe826"
down_revision: Union[str, None] = "f7df23ff0c1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "media_items",
        sa.Column("titles", postgresql.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "media_items",
        sa.Column("descriptions", postgresql.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "source_assets",
        sa.Column("titles", postgresql.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "source_assets",
        sa.Column("descriptions", postgresql.ARRAY(sa.String()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source_assets", "descriptions")
    op.drop_column("source_assets", "titles")
    op.drop_column("media_items", "descriptions")
    op.drop_column("media_items", "titles")
    # ### end Alembic commands ###
