# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Routes media generated by the Izumi agent into a dedicated gallery folder.

The agent authenticates every Creative Studio call with the
``X-User-Authorization`` header, which the auth guard turns into the
``is_agent_request`` context variable. Generation payloads carry no
``folder_id``, so this helper is the single place where agent output is
grouped. The layout is::

    <workspace root>
    └── Izumi Agent/            owned by the workspace owner
        └── <user email>/       owned by the generating user  <- items land here

Ownership matters because the folder permission policy
(:meth:`FolderService.ensure_can_manage_folder`) only lets non-admins modify
folders they created: the shared root therefore belongs to the workspace
owner (the bootstrap admin on the public workspace), while every user keeps
full control of their own sub-folder without being able to touch anyone
else's.

Folder bookkeeping must never fail a generation, so every error path logs
and returns ``None`` (item lands in the workspace root, as before).
"""

import logging

from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from src.common.request_context import is_agent_request
from src.folders.repository.folder_repository import FolderRepository
from src.folders.schema.folder_model import Folder
from src.users.repository.user_repository import UserRepository
from src.users.user_model import UserModel
from src.workspaces.repository.workspace_repository import WorkspaceRepository

logger = logging.getLogger(__name__)

AGENT_OUTPUT_FOLDER_NAME = "Izumi Agent"
# Gemini purple, matching the badge used across the app for the agent.
AGENT_OUTPUT_FOLDER_COLOR = "#8E75B2"


async def _resolve_root_owner(
    db: AsyncSession, workspace_id: int, user: UserModel
) -> tuple[int | None, str]:
    """Returns ``(user_id, email)`` of the workspace owner.

    Falls back to the requesting user when the workspace or its owner cannot
    be resolved, so a missing row never blocks a generation.
    """
    try:
        workspace = await WorkspaceRepository(db).get_by_id(workspace_id)
        if workspace is not None:
            owner = await UserRepository(db).get_by_id(workspace.owner_id)
            if owner is not None and owner.id is not None:
                return owner.id, owner.email
        logger.warning(
            "Workspace %s or its owner not found; agent root folder will be "
            "owned by the requesting user %s",
            workspace_id,
            user.email,
        )
    except Exception as err:  # pylint: disable=broad-except
        logger.warning(
            "Could not resolve owner of workspace %s (%s); agent root folder "
            "will be owned by the requesting user %s",
            workspace_id,
            err,
            user.email,
        )
    return user.id, user.email


async def _get_or_create_folder(
    db: AsyncSession,
    repo: FolderRepository,
    *,
    workspace_id: int,
    parent_id: int | None,
    name: str,
    owner_id: int | None,
    owner_email: str,
) -> int | None:
    """Returns the id of the active folder ``name`` under ``parent_id``,
    creating it (owned by ``owner_id``) when missing."""
    existing = await repo.get_folder_by_name(
        workspace_id=workspace_id, parent_id=parent_id, name=name
    )
    if existing is not None:
        return existing.id

    folder = Folder(
        workspace_id=workspace_id,
        user_id=owner_id,
        user_email=owner_email,
        name=name,
        parent_id=parent_id,
        color=AGENT_OUTPUT_FOLDER_COLOR,
    )
    db.add(folder)
    try:
        await db.commit()
    except IntegrityError:
        # Two agent calls raced on the first generation: the unique index on
        # (workspace_id, parent_id, lower(trim(name))) rejected the second
        # insert, so the winner's row is what we want.
        await db.rollback()
        existing = await repo.get_folder_by_name(
            workspace_id=workspace_id, parent_id=parent_id, name=name
        )
        return existing.id if existing is not None else None

    await db.refresh(folder)
    logger.info(
        "Created agent output folder '%s' (id=%s, parent=%s, owner=%s) in "
        "workspace %s",
        name,
        folder.id,
        parent_id,
        owner_email,
        workspace_id,
    )
    return folder.id


async def resolve_agent_output_folder_id(
    db: AsyncSession, workspace_id: int, user: UserModel
) -> int | None:
    """Returns the id of the user's agent output folder, or ``None``.

    ``None`` is returned for regular (non-agent) requests so callers can pass
    the result straight into ``MediaItemModel(folder_id=...)``. For agent
    requests it resolves ``Izumi Agent/<user email>`` (creating both levels
    on first use) and falls back to the root folder if the per-user child
    cannot be resolved.
    """
    if not is_agent_request.get():
        return None

    repo = FolderRepository(db)
    try:
        owner_id, owner_email = await _resolve_root_owner(
            db, workspace_id, user
        )
        root_id = await _get_or_create_folder(
            db,
            repo,
            workspace_id=workspace_id,
            parent_id=None,
            name=AGENT_OUTPUT_FOLDER_NAME,
            owner_id=owner_id,
            owner_email=owner_email,
        )
        if root_id is None:
            return None

        child_id = await _get_or_create_folder(
            db,
            repo,
            workspace_id=workspace_id,
            parent_id=root_id,
            name=user.email,
            owner_id=user.id,
            owner_email=user.email,
        )
        return child_id if child_id is not None else root_id
    except Exception as err:  # pylint: disable=broad-except
        logger.warning(
            "Could not resolve agent output folder in workspace %s: %s",
            workspace_id,
            err,
        )
        try:
            await db.rollback()
        except Exception:  # pylint: disable=broad-except
            pass
        return None
